<a href="https://colab.research.google.com/github/joshiansu/article-snippets/blob/master/Pegasos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HI!!! 

WELCOME TO PEGASOS ALGORITHM

Contents :

👨🏻‍🏫First cell
- Experiment Class : Contains
        - __init__
        - pegasos : Algorithm implementation
        - cosine_metrics : To check if algorithm is working
        - cosine_check : validation step
        - fwd_exp : Experiment function to perform experiments

👨🏻‍🏫Second Cell
- poly_func : Function to get data (Random data generation)

👨🏻‍🏫Third Cell
- Experimentation

  - How it works
      - Change epochs and lambda_param
      - Run the cell
      - Check if ground truth weights(m) and experiment weights(w) are coming close or not
      - Do the above excercise with GT bias(c) and Pred bias(b)



🐱Results:

Epochs |	lambda_param |	Avg iter time(ms)	|Total time(ms)

1 |	1 |	1.530408859 |	1.530408859


1 |	5 |	1.981496811 |	1.981496811

1 |	10 |	1.479148865 |	1.479148865

5 |	1 |	0.3053665161 |	1.526832581

5 |	5 |	0.288105011 |	1.440525055

5 |	10 |	0.2956867218 |	1.478433609

10 |	10 |	0.1514196396 |	1.514196396

In [54]:
#Pegasos Algorithm

import numpy as np

class Experiment():
    def __init__(self, epochs, lambda_param):
        self.epochs = epochs
        self.lambda_param = lambda_param

    def pegasos(self, X, y, epochs, lambda_param):
        m, n = X.shape
        w = np.zeros(n)
        b = 0
        store_w = []
        store_b = []
        for t in range(1, epochs + 1):
            # print("In EPOCH : {}".format(t))
            i = np.random.randint(m)
            x_i, y_i = X[i], y[i]
            # print(x_i, y_i)
            if y_i * (np.dot(w, x_i) + b) < 1:
                w = (1 - 1/t * lambda_param) * w + 1/lambda_param * y_i * x_i
                b = b + y_i
                # print(w, b)
            else:
                w = (1 - 1/t * lambda_param) * w
                # print(w, b)
            store_w.append(w)
            store_b.append(b)
        return w, b, store_w, store_b
      
    def cosine_metrics(self, arr1, arr2):
        dot_product = np.dot(arr1, arr2.T)

        # Calculate the norms of the arrays
        norm1 = np.linalg.norm(arr1)
        norm2 = np.linalg.norm(arr2)
        # Calculate the cosine similarity
        cosine_similarity = dot_product / (norm1 * norm2)

        return np.linalg.norm(cosine_similarity)
    
    def cosine_check(self, store_w, m):
        try:
          store_cosine = []
          for w in store_w:
              store_cosine.append(self.cosine_metrics(w, m))
        except:
          pass
        return store_cosine

    def fwd_exp(self, X, y, m, c):
        w, b, store_w, store_b = self.pegasos(X, y, self.epochs, self.lambda_param)
        store_cosine = self.cosine_check(store_w, m)
        return w, b, store_w, store_b, store_cosine


In [58]:
# Data Preparation

def poly_func(X):
  m = np.random.rand(X.shape[1])
  c = np.random.rand(1)
  # print(m)
  # print(c)
  y = np.dot(X, m) + c
  return y, m, c

X = np.random.rand(3, 4)
y, m, c = poly_func(X)
print("X :", X)
print("y :", y)
print("m :", m)
print("c :", c)


X : [[0.1672588  0.58760356 0.8373335  0.02784416]
 [0.45835336 0.04043766 0.91946249 0.45042764]
 [0.47535977 0.76357002 0.44157301 0.46444556]]
y : [1.11994672 1.28281751 1.12733623]
m : [0.11778381 0.41999957 0.98434173 0.65679573]
c : [0.01094286]


In [84]:
import time

epochs = 20
lambda_param = 10

a = time.time()
print("TIME REPORT ...")
time_taken = time.time()-a
exp1 = Experiment(epochs, lambda_param)
print("Epochs:", exp1.epochs)
w, b, store_w, store_b, store_cosine = exp1.fwd_exp(X, y, m , c)
print("TOTAL TIME : {}ms".format(time_taken*1000))
print("AVG ITERATION TIME : {}ms".format((time_taken/exp1.epochs)*1000))
print(w, b)
print(m, c)

TIME REPORT ...
Epochs: 20
TOTAL TIME : 0.1513957977294922ms
AVG ITERATION TIME : 0.007569789886474609ms
[0. 0. 0. 0.] 3.3820086985351088
[0.11778381 0.41999957 0.98434173 0.65679573] [0.01094286]


<ipython-input-54-3ec8aeb9ff42>:39: RuntimeWarning: invalid value encountered in double_scalars
  cosine_similarity = dot_product / (norm1 * norm2)


In [70]:
store_w

[array([0.11759674, 0.01037483, 0.23590052, 0.11556329]),
 array([-0.17639511, -0.01556224, -0.35385077, -0.17334494]),
 array([0.11759674, 0.01037483, 0.23590052, 0.11556329]),
 array([-0.02939919, -0.00259371, -0.05897513, -0.02889082]),
 array([-0., -0., -0., -0.])]

In [71]:
store_b

[1.282817509093661,
 1.282817509093661,
 1.282817509093661,
 1.282817509093661,
 1.282817509093661]

In [72]:
store_cosine

[0.8984164272742101,
 0.8984164272742099,
 0.8984164272742101,
 0.8984164272742101,
 nan]